class ExplorerPageLocators:
    TITLE = '//*[@id="__next"]/div/div/div[1]/div/h1'
    DESCRIPTION = '//*[@id="__next"]/div/div/div[1]/p'
    GO_TO_DOCUMENTATION_BUTTON = '//*[@id="__next"]/div/div/div[1]/div/a'
    ADVERTISING = '//*[@id="__next"]/div/div/div[2]/div/div/a/img'
    SECTIONS = '//*[@id="__next"]/div/div/div[3]/div/div'
    API_URL = '//*[@id="__next"]/div/div/div[4]'
    USER_LIST_SECTION = '//*[@id="__next"]/div/div/div[3]/div/div[1]'
    USER_PROFILE_SECTION = '//*[@id="__next"]/div/div/div[3]/div/div[2]'
    POST_LIST_SECTION = '//*[@id="__next"]/div/div/div[3]/div/div[3]'
    USER_POSTS_SECTION = '//*[@id="__next"]/div/div/div[3]/div/div[4]'
    COMMENT_LIST_SECTION = '//*[@id="__next"]/div/div/div[3]/div/div[5]'
    TAG_LIST_SECTION = '//*[@id="__next"]/div/div/div[3]/div/div[6]'
    POST_BY_TAG_SECTION = '//*[@id="__next"]/div/div/div[3]/div/div[7]'
    RESPONSE_BODY = '//*[@id="__next"]/div/div/div[5]/div/div'
