class ListOfDataMainPage:
    FUTURES = [
        [
            "REST API - DummyAPI is a RESTful online fake API, publicly accessible via https."
        ],
        ["GraphQL - Access static fake data via the GraphQL interface."],
        [
            "Cross platform - application/json format, Mock JSON dummy API server. Available via REST endpoints or GraphQL."
        ],
        [
            "Data relations - Various data structures and types, with a different type of relations. Including images, text, links, map location data, datetime, and emails."
        ],
        [
            "24/7 uptime - DummyAPI deployed on Google Cloud Platform, which provides 99.9% uptime and fast response time."
        ],
        [
            "Free to use - Free for all users, up to 500 requests per day on a beta phase. Support us on Patreon to get unlimited access."
        ],
    ]
    USE_CASES_LEFT = [
        [
            "Education, Learning - suitable fake API for any types of tutorials. We try to cover all possible cases that you need to work on real production projects."
        ],
        [
            "Free Image API - We have a lot of dummy data. You can simply use DummyAPI as a free image API, including metadata for every image. Tags, text and a source link of the image source."
        ],
        [
            "Demo page, Portfolio - our non-auth fake API data is perfect for creating a presentation page for libraries and modules. No server-side code, deploying, infrastructure setups, or storing data anymore."
        ],
    ]
    USE_CASES_RIGHT = [
        ["Testing - Dummy API for testing JSON, go deep with Unit tests for Rest API."],
        [
            "Skill evaluation - Want to give your future employee an assignment? Our fake API is great for covering all required areas, starting from simple pagination till auth flow."
        ],
        [
            "Any other cases - We have no restriction for dummy API usage. Data is not real, but close to it, so you have a wide range for play around"
        ],
    ]
    USAGE_STATISTICS = [
        ["Status Deploying on GCF and maintain 99.99% uptime. API working normally"],
        ["Response Time Average response time in your region. 327ms"],
        ["API Call's per day Last 100 days statistic of API calls per each day."],
    ]
    OUR_SPONSORS = "You can become our sponsor on Patreon, we will place a logo and a link to your website in current section.There two types of sponsorship: 1) 10$+ - We will place a link to your website and a logo.2) 50$+ - We will place a link(follow) to your website and a logo on a top of a section, and bigger. Also you can provide a small text snippet that describes your company"
    RELATED_LINKS_LEFT = [
        ["Contact Us Email: dummyapi.io@gmail.com"],
        [
            "Community We are trying to do our best for you. That why we create a telegram community to post important updates about project. And Telegram Chat where you can report a bug or bring some ideas about improvements. DummyAPI Telegram Community DummyAPI Telegram Chat"
        ],
    ]
    RELATED_LINKS_RIGHT = [
        [
            "Copyright Notices User Data - All user pictures and data is fake and randomly generated by open-source third-party service randomuser.me. Additional license information by link randomuser.me/copyright. Post - All pictures used in PostData is free to use and was fetched from unsplash.com. Additional license information by link unsplash.com/license."
        ],
        [
            "Side Projects RGBTOHEX.PAGE - Feel free to check our side project. This site cover everything about color in development. Explore Color Models(RGB, CMYK, HSL) and various of color palettes(Brand Colors, Color Bit Depth, Color Blind Palettes) https://rgbtohex.page"
        ],
    ]
